@startuml

package "Lot" {
    class LotController {
        + createLot(lot: Lot): ResponseEntity<Lot>
        + getLot(id: int): ResponseEntity<Lot>
    }

    class LotNotFoundAdvice
    class LotNotFoundException

    class LotRepository {
        + findById(id: int): Lot
    }

    class LotService {
        + createLot(nomArticle: string, details: string, enchereDepart: decimal, dateFin: date, heureFin: time, description: string, categorieId: int, imageUrl: string): Lot
        + findLotById(id: int): Lot
    }

    class LotEntity {
        - id: int
        - nomArticle: string
        - details: string
        - enchereDepart: decimal
        - status: enum
        - dateFin: date
        - heureFin: time
        - description: string
        - categorieId: int
        - sousCategorieId: int
        - imageUrl: string
    }

    LotNotFoundAdvice ..> LotNotFoundException
    LotController ..> LotNotFoundException
    LotController ..> LotRepository
    LotController ..> LotEntity
    LotService ..> LotController
    LotService --> LotRepository
    LotRepository --> LotEntity
}

@enduml
