@startuml

skinparam classAttributeIconSize 0

class Utilisateur {
    - nom_utilisateur : String
    - nom : String
    - prenom : String
    - email : String
    - mot_de_passe : String
    - telephone : String
    - rue : String
    - npa : String
    - localite : String
    - solde : Decimal
    - date_creation : Date
}

class Lot {
    - id_lot : Long
    - nomArticle : String
    - details : String
    - statut : Enum
    - enchere : Decimal
    - dateHeureFin : Date
    - description : String
    - id_categorie : Long
    - imageUrl : String
}

class Categorie {
    - id_categorie : Long
    - nom : String
    - id_parent : Long
}

class Enchere {
    - id_enchere : Long
    - montant : Decimal
    - dateEnchere : Date
    - nom_utilisateur : String
    - id_lot : Long
}

Utilisateur "1 " --> "0..n " Lot : "possède"
Lot "1" --> "0..n" Categorie : "appartient à"
Categorie "1" --> "0..n" Categorie : "catégorie parente/sous-catégorie"

@enduml
