@startuml

skinparam classAttributeIconSize 0

class Lot {
    - id_lot : Long
    - nomArticle : String
    - details : String
    - statut : Enum
    - enchereDepart : Decimal
    - dateHeureFin : Date
    - description : String
    - id_categorie : Long
    - imageUrl : String
}

class Categorie {
    - id_categorie : Long
    - nom : String
    - id_parent : Long
}

Lot "1" --> "0,n" Categorie : "appartient à"
Categorie "1" --> "0,n" Categorie : "catégorie parente/sous-catégorie"

@enduml
