@startuml
entity Lot {
  + id_lot : Long <<PK>>
  nom_article : varchar
  details : varchar
  satuts : enum
  enchere_depart : decimal
  date_heure_fin : date
  description : text
  id_categorie : Long <<FK>>
  id_sous-categorie : Long <<FK>>
  image_url : varchar
}
@enduml